// [AUNEA-UAT-ENGINE-020] START — Engine adapter regression
const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const vm=require('node:vm');const path=require('node:path');const code=fs.readFileSync(path.join(__dirname,'..','app-engine-adapter-v1.js'),'utf8');const e={id:'E1',title:'Test',answers:{DF011:'Proceso',DF086:['VISIBILITY']},answerDetails:{},processSteps:[{id:'S1',status:'ACTIVE'}],frictions:[{id:'F1',status:'ACTIVE',friction_type:'P03',observable_signal:'Se reintroduce cada solicitud',evidence_type:'EV02',affected_steps:['S1']}],economicInputs:[],risks:[],engineGates:{process_design_first:'NO',existing_tool_can_close:'NO',unstructured_interpretation_need:'NO',bounded_action_space:'NO',management_visibility_need:'YES'}};const ctx={console,schema:{friction_pain_map:[{Friction_Type_ID:'P03',Pain_ID:'P03'}]},activeFrictions:e=>(e.frictions||[]).filter(x=>x.status!=='SUPERSEDED'),activeSteps:e=>(e.processSteps||[]).filter(x=>x.status!=='SUPERSEDED'),normalizeArray:v=>Array.isArray(v)?v:(v==null||v===''?[]:[v]),currentEng:()=>e,fieldOptions:()=>[],esc:v=>String(v??''),attr:v=>String(v??''),openModal:()=>{},markDirty:()=>{},closeModal:()=>{},now:()=>'',runDiagnosis:()=>{},state:{backendOnline:true},canonicalMissingRequired:()=>[],render:()=>{},toast:()=>{},document:{getElementById:()=>null,querySelectorAll:()=>[]}};vm.createContext(ctx);vm.runInContext(code,ctx);test('no hardcoded recommendation guard remains in canonical adapter',()=>{assert.doesNotMatch(code,/unresolvedRecommendationAdapter\s*=\s*true/)});test('client-declared concrete friction can become concrete evidence input without deciding Pain state',()=>{const p=ctx.buildBackendPayload(e);assert.equal(p.pain_signals[0].direct_mechanism_present,true);assert.equal(p.pain_signals[0].concrete_evidence_present,true);assert.equal(p.evidence[0].type,'CLIENT_DECLARED');});test('five canonical engine gates map to backend inputs',()=>{const p=ctx.buildBackendPayload(e);assert.equal(p.process_design_preconditions_ok,true);assert.equal(p.existing_tool_can_cover,false);assert.equal(p.requires_management_visibility,true);assert.equal(p.requires_unstructured_ai_assistance,false);assert.equal(p.requires_bounded_agent_action,false)});test('commercial scope is omitted unless explicitly captured',()=>{const p=ctx.buildBackendPayload(e);assert.equal(Object.hasOwn(p,'commercial_scope'),false)});test('scenario remains backend-owned',()=>{assert.match(code,/\/v1\/diagnose/);assert.doesNotMatch(code,/one_off_eur\s*=/)});
test('the Engine Gates review is framed as "Confirmación del consultor antes de calcular", not another discovery section — never phrased as validating/asking the client',()=>{
  assert.match(code,/Confirmación del consultor antes de calcular/);
  assert.doesNotMatch(code,/Validar inputs para Recommendation/,'the old technical-sounding title must be gone');
  assert.match(code,/Confirmar y calcular/);
});

// The adapter owns state→payload conversion, HTTP and structured outputs — never capture UI.
// Risk capture UI lives in app-risk-v1.js and is covered by risk-capture-v1.test.cjs.
test('the engine adapter contains no capture UI: no risk/economic modal markup, no capture field ids',()=>{
  assert.doesNotMatch(code,/<details class="step-group"/,'capture modals must not live in the adapter');
  ['riskCat','riskDesc','riskLike','riskImpact','econDriver','econActive'].forEach(fid=>{
    assert.doesNotMatch(code,new RegExp(`id="${fid}"`),`${fid} is capture UI and must not live in the adapter`);
  });
  assert.doesNotMatch(code,/function addRisk\(|function addEconomic\(/,'capture entry points belong to their own modules');
});
// [AUNEA-UAT-ENGINE-020] END
