// [AUNEA-UAT-ENGINE-020] START — Engine adapter regression
const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const vm=require('node:vm');const path=require('node:path');const code=fs.readFileSync(path.join(__dirname,'..','app-engine-adapter-v1.js'),'utf8');const e={id:'E1',title:'Test',answers:{DF011:'Proceso',DF086:['VISIBILITY']},answerDetails:{},processSteps:[{id:'S1',status:'ACTIVE'}],frictions:[{id:'F1',status:'ACTIVE',friction_type:'P03',observable_signal:'Se reintroduce cada solicitud',evidence_type:'EV02',affected_steps:['S1']}],economicInputs:[],risks:[],engineGates:{process_design_first:'NO',existing_tool_can_close:'NO',unstructured_interpretation_need:'NO',bounded_action_space:'NO',management_visibility_need:'YES'}};const ctx={console,schema:{friction_pain_map:[{Friction_Type_ID:'P03',Pain_ID:'P03'}]},activeFrictions:e=>(e.frictions||[]).filter(x=>x.status!=='SUPERSEDED'),activeSteps:e=>(e.processSteps||[]).filter(x=>x.status!=='SUPERSEDED'),normalizeArray:v=>Array.isArray(v)?v:(v==null||v===''?[]:[v]),currentEng:()=>e,fieldOptions:()=>[],esc:v=>String(v??''),attr:v=>String(v??''),openModal:()=>{},markDirty:()=>{},closeModal:()=>{},now:()=>'',runDiagnosis:()=>{},state:{backendOnline:true},canonicalMissingRequired:()=>[],render:()=>{},toast:()=>{},document:{getElementById:()=>null,querySelectorAll:()=>[]}};vm.createContext(ctx);vm.runInContext(code,ctx);test('no hardcoded recommendation guard remains in canonical adapter',()=>{assert.doesNotMatch(code,/unresolvedRecommendationAdapter\s*=\s*true/)});test('client-declared concrete friction can become concrete evidence input without deciding Pain state',()=>{const p=ctx.buildBackendPayload(e);assert.equal(p.pain_signals[0].direct_mechanism_present,true);assert.equal(p.pain_signals[0].concrete_evidence_present,true);assert.equal(p.evidence[0].type,'CLIENT_DECLARED');});test('five canonical engine gates map to backend inputs',()=>{const p=ctx.buildBackendPayload(e);assert.equal(p.process_design_preconditions_ok,true);assert.equal(p.existing_tool_can_cover,false);assert.equal(p.requires_management_visibility,true);assert.equal(p.requires_unstructured_ai_assistance,false);assert.equal(p.requires_bounded_agent_action,false)});test('commercial scope is omitted unless explicitly captured',()=>{const p=ctx.buildBackendPayload(e);assert.equal(Object.hasOwn(p,'commercial_scope'),false)});test('scenario remains backend-owned',()=>{assert.match(code,/\/v1\/diagnose/);assert.doesNotMatch(code,/one_off_eur\s*=/)});
test('addRisk groups riskCat/riskDesc/riskLike/riskImpact into an open layer-1 group and the rest into a collapsed layer-2 group, same field ids and RiskInput shape as before',()=>{
  const groups=[...code.matchAll(/<details class="step-group"( open)?><summary>([^<]+)<\/summary>/g)];
  assert.equal(groups.length,2);
  assert.equal(groups[0][1],' open','layer 1 (Riesgo) must be open by default');
  assert.equal(groups[0][2],'Riesgo');
  assert.equal(groups[1][1],undefined,'layer 2 (controles y resto) must start collapsed');
  ['riskCat','riskDesc','riskLike','riskImpact','riskRev','riskControls','riskSensitive','riskMat','riskCritical'].forEach(fid=>{
    assert.match(code,new RegExp(`id="${fid}"`),`${fid} must still exist`);
  });
});
// [AUNEA-UAT-ENGINE-020] END
