// [AUNEA-FE-PAGE-PROJECTS-010] START — Delivery and learning surface
// PURPOSE: Operate Project-owned actuals/outcomes and review backend specifications before handoff.
// SOURCE: DEC-023/025/054/055; Architecture Contract v1.3 P06/SPEC.
// INPUTS: linked Project sources and SolutionSpecification backend response.
// OUTPUTS: Spanish project forms, historical references, specification review and measured comparisons.
// SIDE_EFFECTS: DOM, audit, optional specification endpoint; never recalculates diagnostic engines.
// CHANGE_RISK: HIGH.
function projectsPage(){
  return pageTop('Proyectos','Ejecución y resultados reales vinculados al estudio y a la decisión aprobada.')+(state.projects.length?state.projects.map(p=>{
    const src=projectSource(p),r=src.review;
    const actuals=(p.actuals||[]).map(a=>`<tr><td>${esc(a.phase)}</td><td>${a.hours??'—'}</td><td>${a.costEur??'—'}</td><td>${esc(a.evidence)}</td></tr>`).join('');
    const outcomes=projectLearning(p).map(o=>`<tr><td>${esc(PROJECT_OUTCOME_FIELDS.find(f=>f[0]===o.field)?.[1]||o.field)}</td><td>${o.estimate??'No disponible'}</td><td>${o.value}</td><td>${o.delta??'No disponible'}</td><td>${esc(o.unit)}</td><td>${esc(o.period)}</td><td>${esc(o.evidence)}</td></tr>`).join('');
    return section(esc(p.name),`${esc(companyById(p.companyId)?.name||'Empresa no disponible')} · ${esc(p.status)}`,`<p><b>Área:</b> ${esc(labelFrom('REF_DOMAIN',p.businessAreaId)||'—')}</p><p>Contactos: ${esc((p.contactIds||[]).map(contactById).filter(Boolean).map(contactFullName).join(', ')||'Sin contactos vinculados')}</p><p>Estudio: ${esc(src.engagement?.title||'No disponible')} · Escenario: ${esc(r?.sources.scenario.scenario_name||'Referencia histórica pendiente')} · TO-BE: ${p.tobeRef?.version??'—'} · Especificación: ${p.solutionSpecificationRef?.version??'—'}</p><button class="btn" data-open-eng="${attr(p.engagementId)}" data-open-eng-page="resultados">Abrir estudio origen</button><button class="btn" data-project-actual="${attr(p.id)}">Registrar ejecución real</button><button class="btn" data-project-outcome="${attr(p.id)}">Registrar resultado medido</button><h3>Ejecución real</h3><div class="table-wrap"><table class="data-table"><thead><tr><th>Fase</th><th>Horas</th><th>Coste EUR</th><th>Evidencia</th></tr></thead><tbody>${actuals||'<tr><td colspan="4">Sin registros reales todavía.</td></tr>'}</tbody></table></div><h3>Estimado frente a real</h3><p>Estimación del escenario aprobado. Trabajo activo, espera y ahorro de caja se comparan por separado.</p><div class="table-wrap"><table class="data-table"><thead><tr><th>Medición</th><th>Estimado</th><th>Real</th><th>Diferencia</th><th>Unidad</th><th>Periodo</th><th>Evidencia</th></tr></thead><tbody>${outcomes||'<tr><td colspan="7">Sin mediciones. No se generan valores por defecto.</td></tr>'}</tbody></table></div>`);
  }).join(''):'<div class="empty"><h2>Aún no hay proyectos</h2><p>Registra la decisión de implementación desde Trabajo interno después de presentar los resultados.</p></div>');
}
function projectActualModal(projectId){openModal('Registrar ejecución real',`<div class="form-grid"><div class="field"><label>Fase realizada</label><input id="actualPhase"></div><div class="field"><label>Horas reales</label><input type="number" min="0" step="any" id="actualHours"></div><div class="field"><label>Coste real (EUR)</label><input type="number" min="0" step="any" id="actualCost"></div><div class="field full"><label>Evidencia / referencia</label><textarea id="actualEvidence"></textarea></div></div>`,()=>{const val=k=>document.getElementById(k).value,r=addProjectActual(projectId,{phase:val('actualPhase'),hours:val('actualHours'),cost:val('actualCost'),evidence:val('actualEvidence')});if(!r.ok)return toast(r.error);closeModal();render()})}
function projectOutcomeModal(projectId){openModal('Registrar resultado medido',`<div class="form-grid"><div class="field full"><label>Medición existente en el escenario</label><select id="outcomeField">${PROJECT_OUTCOME_FIELDS.map(f=>`<option value="${f[0]}">${f[1]} (${f[2]})</option>`).join('')}</select></div><div class="field"><label>Valor anual medido</label><input type="number" min="0" step="any" id="outcomeValue"></div><div class="field"><label>Periodo de medición</label><input id="outcomePeriod" placeholder="Ej. septiembre 2026 – agosto 2027"></div><div class="field full"><label>Evidencia / fuente de la medición</label><textarea id="outcomeEvidence"></textarea></div></div>`,()=>{const val=k=>document.getElementById(k).value,r=addProjectOutcome(projectId,{field:val('outcomeField'),value:val('outcomeValue'),period:val('outcomePeriod'),evidence:val('outcomeEvidence')});if(!r.ok)return toast(r.error);closeModal();render()})}
function currentSpecification(e){const review=approvedOutputReview(e);return [...(e?.solutionSpecifications||[])].reverse().find(s=>s.sourceReviewId===review?.id)||null}
async function generateProjectSpecification(e,targetPlatform=''){
  const review=approvedOutputReview(e);if(!review)return toast('Aprueba primero los resultados de esta versión.');
  const sourceId=review.id,tobe=approvedTobeForClient(e);
  try{
    const request={selected_scenario:review.sources.scenario,target_platform:targetPlatform||null,notes:[`Propuesta TO-BE aprobada v${tobe.version}; AS-IS v${tobe.sourceSnapshotVersion}`,...tobe.items.map(i=>`${i.sourceStepName}: ${i.transformation}. ${i.problemResolved||''}`)]};
    const response=await fetch(`${state.backendUrl}/v1/solution-specifications/generate`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({engagement:buildBackendPayload(e),diagnostic:review.sources.output,request})});
    if(!response.ok)throw new Error(await response.text());const data=await response.json();
    if(approvedOutputReview(e)?.id!==sourceId)throw new Error('Los resultados cambiaron durante la generación; vuelve a generar la especificación.');
    if(!data.specification_id||data.engagement_id!==e.id||data.source_scenario_id!==review.sources.scenario.scenario_id)throw new Error('La especificación no coincide con el estudio y escenario aprobados.');
    const history=e.solutionSpecifications||(e.solutionSpecifications=[]);
    history.push({id:id('SPEC'),version:history.length+1,sourceReviewId:review.id,status:'DRAFT',createdAt:now(),data:frozenCopy(data)});markDirty('Especificación del backend recibida como borrador');render();
  }catch(err){toast('No se pudo generar la especificación: '+err.message)}
}
function advanceSpecification(e){const s=currentSpecification(e);if(!s||s.data.status==='BLOCKED_SCENARIO')return false;const next={DRAFT:'REVIEWED',REVIEWED:'APPROVED_FOR_CLIENT'}[s.status];if(!next)return false;s.status=next;s.reviewedAt=now();markDirty('Revisión humana de especificación: '+next);return true}
function implementationPage(){
  const e=currentEng(),review=approvedOutputReview(e),s=currentSpecification(e),ready=projectDecisionReadiness(e),labels={DRAFT:'Borrador',REVIEWED:'Revisado',APPROVED_FOR_CLIENT:'Aprobado para cliente',PUBLISHED:'Publicado'};
  if(!review)return pageTop('Decisión e implementación','Aprueba los resultados antes de preparar la implementación.','<button class="btn" data-page="revision">Revisión humana</button>');
  const actions=`<button class="btn" data-page="modoresultados">Presentar resultados</button>${ready.ok?'<button class="btn btn-primary" id="decideImplementation">Registrar decisión de implementar y crear proyecto</button>':''}`;
  return pageTop('Decisión e implementación','El proyecto referencia el escenario, el TO-BE y la especificación aprobados.',actions)+section('Especificación de solución','La genera el backend sobre el escenario seleccionado; su preparación técnica no sustituye la aprobación humana.',`<div class="field"><label>Plataforma de implementación acordada (opcional)</label><input id="specPlatform"></div><button class="btn" id="generateSpecification">Generar versión de especificación</button>${s?`<h3>Versión ${s.version} · ${labels[s.status]}</h3><p>${s.data.status==='BLOCKED_NOT_SYSTEM'?'El escenario no requiere una implementación System. Se conserva la referencia del backend.':s.data.status==='READY_FOR_BUILD'?'Preparación técnica completa.':s.data.status==='BLOCKED_SCENARIO'?'Escenario bloqueado por el backend.':'Existen datos de implementación pendientes; no está lista para construir.'}</p><p>${esc(s.data.objective||'')}</p><p>Requisitos pendientes: ${(s.data.missing_information||[]).length}. Revisa el documento completo antes de aprobar.</p><button class="btn" id="downloadSpecification">Descargar especificación completa</button>${['DRAFT','REVIEWED'].includes(s.status)&&s.data.status!=='BLOCKED_SCENARIO'?`<button class="btn" id="approveSpecification">${s.status==='DRAFT'?'Marcar especificación revisada':'Aprobar especificación para cliente'}</button>`:''}`:'<p>No hay especificación generada.</p>'}`)+(!ready.ok?`<div class="notice">${esc(ready.error)}</div>`:'');
}
function downloadProjectSpecification(e){const s=currentSpecification(e);if(!s)return;const url=URL.createObjectURL(new Blob([JSON.stringify(s.data,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download=`AUNEA_Especificacion_v${s.version}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),500)}
function bindProjectPages(){
  const by=id=>document.getElementById(id),e=currentEng();
  document.querySelectorAll('[data-project-actual]').forEach(b=>b.onclick=()=>projectActualModal(b.dataset.projectActual));document.querySelectorAll('[data-project-outcome]').forEach(b=>b.onclick=()=>projectOutcomeModal(b.dataset.projectOutcome));
  if(by('generateSpecification'))by('generateSpecification').onclick=()=>generateProjectSpecification(e,by('specPlatform').value.trim());
  if(by('approveSpecification'))by('approveSpecification').onclick=()=>{if(advanceSpecification(e))render()};
  if(by('downloadSpecification'))by('downloadSpecification').onclick=()=>downloadProjectSpecification(e);
  if(by('decideImplementation'))by('decideImplementation').onclick=createProjectFromEngagement;
}
// [AUNEA-FE-PAGE-PROJECTS-010] END
